### PR TITLE
Add a custom salt option for hash generation

### PR DESCRIPTION
**Pull request by BYK**
This allows mass changing hashes when something goes wrong.

### CODE REVIEW

**Comment by Digikid13** [comment]
👀

**Comment by BYK** [comment]
@Munter we are doing a depth-first post-order. I think our tanglement with Grunt and allowing multiple entry points masks that.

The reason we need a cache busting system like this is because recently CloudFlare messed some of our PNG images and since they almost never change, we need to invalidate the hashses to break infinite caching.

**Comment by Munter** [comment]
Oh dear... Never mind me then :)

**Review by Met48 — APPROVED** [review]
lgtm. Readme could use an update documenting the new option.

**Pull request merged**
